### ISSUE TITLE
For text match problem, what is the different between question-question match and question-answer match?

### ISSUE THREAD

**Issue by guotong1988** [AdeDZY/SIGIR19-BERT-IR#1]
I know question-question match is a text similarity problem.
What about question-answer match or question-doc match? It is used in information retrieval.
question-question match is indeed text similarity. But how do you define question-answer similarity?
Thank you!!

**Comment by AdeDZY** [comment]
From my point of view, in general, text matching models can be used to all
of these problems. But the best model may vary depending on the exact task.
