### ISSUE TITLE
Why FLAGS.max_seq_length=128?

### ISSUE THREAD

**Issue by zh-zheng** [AdeDZY/SIGIR19-BERT-IR#3]
Hi!
I am confused why in the run_qe_classifier.py `FLAGS.max_seq_length` is set to 128? The sliding window length is 150 that is longer than max_seq_length.

Thanks!

**Comment by AdeDZY** [comment]
Hi,

Sorry for causing the confusion. This is a default parameter that can be changed. You can take a look at the google colab notebooks to see the specific settings I used in different experiments. In general, it should be set to 256.

**Comment by zh-zheng** [comment]
thanks.
