### ISSUE TITLE
.trec.with_json

### ISSUE THREAD

**Issue by Forlogen** [AdeDZY/SIGIR19-BERT-IR#5]
Hi, I have read the README.md several times but still don't know how to get .trec.with_json. May be I missed something, Can you tell me some details about it, thanks.

**Comment by AdeDZY** [comment]
Hi, basically you need an initial document ranking (trec format), and attach the document contents to the trec file.

The inital document rankings (.trec files) can be found under the "Initial Document Rankings
" secton in this webpage: http://boston.lti.cs.cmu.edu/appendices/SIGIR2019-Zhuyun-Dai/ 

A line in the .trec file looks like:
622 Q0 LA032190-0143 1 -7.19601 indri 
where 622 is the query ID, LA032190-0143 is the document ID.

Next, you need to look up these documents from the collection, optionally split them into passages, and attach them to the trec file.

For BERT-FirstP:
622 Q0 LA032190-0143 1 -7.19601 indri # {title:"...", doc:"..content of documents.."}

For BERT-MaxP and BERT-AvgP: 
622 Q0 LA032190-0143_1 1 -7.19601 indri # {title:"...", doc:"..content of first passage.."}
622 Q0 LA032190-0143_2 1 -7.19601 indri # {title:"...", doc:"..content of second passage.."}
622 Q0 LA032190-0143_3 1 -7.19601 indri # {title:"...", doc:"..content of third passage.."}

**Comment by Forlogen** [comment]
Thank you very much for your reply. I will process dataset carefully again. Thank you again and  have a nice day.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Dai Zhuyun (戴竹韵)<mailto:notifications@github.com>
发送时间: 2019年11月14日 0:36
收件人: AdeDZY/SIGIR19-BERT-IR<mailto:SIGIR19-BERT-IR@noreply.github.com>
抄送: dyliang<mailto:18dyliang@stu.edu.cn>; Author<mailto:author@noreply.github.com>
主题: Re: [AdeDZY/SIGIR19-BERT-IR] .trec.with_json (#5)


Hi, basically you need an initial document ranking (trec format), and attach the document contents to the trec file.

The inital document rankings (.trec files) can be found under the "Initial Document Rankings
" secton in this webpage: http://boston.lti.cs.cmu.edu/appendices/SIGIR2019-Zhuyun-Dai/

A line in the .trec file looks like:
622 Q0 LA032190-0143 1 -7.19601 indri
where 622 is the query ID, LA032190-0143 is the document ID.

Next, you need to look up these documents from the collection, optionally split them into passages, and attach them to the trec file.

For BERT-FirstP:
622 Q0 LA032190-0143 1 -7.19601 indri # {title:"...", doc:"..content of documents.."}

For BERT-MaxP and BERT-AvgP:
622 Q0 LA032190-0143_1 1 -7.19601 indri # {title:"...", doc:"..content of first passage.."}
622 Q0 LA032190-0143_2 1 -7.19601 indri # {title:"...", doc:"..content of second passage.."}
622 Q0 LA032190-0143_3 1 -7.19601 indri # {title:"...", doc:"..content of third passage.."}
