### ISSUE TITLE
Where is nDCG evaluation?

### ISSUE THREAD

**Issue by ryangawei** [AdeDZY/SIGIR19-BERT-IR#6]
In run_qe_classifier.py there is only accuracy when evaluating the model. Can you provide any code on how you do nDCG@20 evaluation in your paper?

**Comment by AdeDZY** [comment]
Hi,
Additional steps are required to evaluate retrieval metrics, e.g., MAP and NDCG.

1. After the evaluation step, for an input file (fold1.trec.with_josn), the code will output the bert predictions (test_result.tsv).

2. In tools/, there are scripts to convert bert predictions to a document ranking file.
If you split document into passages:

`bert_passage_result_to_trec.py fold1.trec.with_josn test_result.tsv fold1_ranking.trec --aggregation maxp -M 100`

If documents are not split:
`bert_doc_result_to_trec.py fold1.trec.with_josn test_result.tsv fold1_ranking.trec -M 100`

3. decompress tools/trec_eval_latest.tar.gz, compile trec_eval (make). Then:
trec_eval qrels_file fold1_ranking.trec -M 100 -m ndcg_cut -m official
qrels_file is the TREC qrel file (relevance judgment), which is provided [here](http://boston.lti.cs.cmu.edu/appendices/SIGIR2019-Zhuyun-Dai/), together with the initial document rankings.

**Comment by ryangawei** [comment]
> Hi,
> Additional steps are required to evaluate retrieval metrics, e.g., MAP and NDCG.
> 
> 1. After the evaluation step, for an input file (fold1.trec.with_josn), the code will output the bert predictions (test_result.tsv).
> 2. In tools/, there are scripts to convert bert predictions to a document ranking file.
>    If you split document into passages:
> 
> `bert_passage_result_to_trec.py fold1.trec.with_josn test_result.tsv fold1_ranking.trec --aggregation maxp -M 100`
> 
> If documents are not split:
> `bert_doc_result_to_trec.py fold1.trec.with_josn test_result.tsv fold1_ranking.trec -M 100`
> 
> 1. decompress tools/trec_eval_latest.tar.gz, compile trec_eval (make). Then:
>    trec_eval qrels_file fold1_ranking.trec -M 100 -m ndcg_cut -m official
>    qrels_file is the TREC qrel file (relevance judgment), which is provided [here](http://boston.lti.cs.cmu.edu/appendices/SIGIR2019-Zhuyun-Dai/), together with the initial document rankings.

Thank you for your answer! I'll check that out.
