### ISSUE TITLE
Using Pre-trained Bing-augmented BERT Model

### ISSUE THREAD

**Issue by jibrilfrej** [AdeDZY/SIGIR19-BERT-IR#8]
Hello,

I am trying to use the Pre-trained Bing-augmented BERT Model provided at http://boston.lti.cs.cmu.edu/appendices/SIGIR2019-Zhuyun-Dai/ but I cannot find any instructions or code example to load the model.

Would it be possible to have an example to load the pre-trained model?

Thanks

**Comment by AdeDZY** [comment]
Hi, 

Thank you for being interested in our work! You can download the model, and you the following example:
https://colab.research.google.com/drive/1qFGmEz5SZrsGui5HHAmiS_geppJQy8b4

Let me know if you come into any issues.

**Comment by jibrilfrej** [comment]
Thanks !!!! 

I will close the issue once I manage to run the example.
